version: '3'  # Docker Composeのバージョン
services:
  
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: 'calendar'
      MYSQL_USER: 'murata'
      MYSQL_USER: 'P@ssw0rd'
      TZ: "Asia/Tokyo"
    restart: 'always'
    env_file: docker-compose.env
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-net

  web:  # コンテナに名前をつける
    build: 
      context: .  # Dockerfileがあるディレクトリへのパス
      #dockerfile: Dockerfile_${DOCKER_FILE_ENV}
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    env_file: docker-compose.env
    command: heroku_env.sh
    networks:
      - app-net
    depends_on:
      - mysql
  
  nginx1:
    build: .
    image: nginx:1.13.5-alpine
    container_name: nginx1
    env_file: docker-compose.env
    depends_on:
      - web
    tty: true
    #command: sh ./local_env.sh
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    networks:
      - app-net



networks:
  app-net:
    driver: bridge

