version: '3'  # Docker Composeのバージョン
services:
  
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: 'calendar'
      MYSQL_USER: 'murata'
      MYSQL_USER: 'P@ssw0rd'
      TZ: "Asia/Tokyo"
    restart: 'always'
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    # app_net:
    #   ipv4_address: 172.16.238.10
    #   ipv6_address: 2001:3984:3989::10
    networks:
      - app-net

  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/www/boatcalendar
    env_file: docker-compose.env
    networks:
      - app-net
    depends_on:
      - mysql
    # command: sh ./wait-for-it.sh mysql python manage.py runserver 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
             
    # app_net:
    #   ipv4_address: 172.16.238.11
    #   ipv6_address: 2001:3984:3989::11
  
  nginx1:
    build: .
#     context: <dockerfileのパス:./hogehoge>
#     dockerfile: <dockerfile名:xxx.dokerfile>
#   container_name: <作成するコンテナ名?>
    image: nginx:1.13.5-alpine
    container_name: nginx1
    depends_on:
      - web
    tty: true
    ports:
      - 8080:80
    volumes:
      # - ./proj/var/www/html:/var/www/html
      - .:/var/www/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-net



networks:
  app-net:
    driver: bridge

