# Generated by Django 2.2.2 on 2020-02-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=100, verbose_name='苗字')),
                ('firstName', models.CharField(max_length=100, verbose_name='名前')),
                ('isRower', models.BooleanField(default=True, verbose_name='漕手')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='app.People', verbose_name='コーチ')),
            ],
        ),
    ]
