# Generated by Django 2.2.2 on 2020-02-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='User',
        ),
    ]
