# Generated by Django 3.0.3 on 2020-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200214_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='people',
        ),
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.IntegerField(default=0, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='plan',
            name='isRow',
            field=models.BooleanField(default=False, verbose_name='乗艇日'),
        ),
        migrations.AddField(
            model_name='plan',
            name='menu',
            field=models.CharField(default=99, max_length=100, verbose_name='メニュー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='month',
            field=models.IntegerField(default=0, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='plan',
            name='year',
            field=models.IntegerField(default=0, verbose_name='年'),
        ),
    ]
