# Generated by Django 3.0.5 on 2020-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200217_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=100, verbose_name='familyname')),
                ('firstName', models.CharField(max_length=100, verbose_name='firstname')),
                ('isRower', models.BooleanField(default=True, verbose_name='漕手')),
                ('username', models.CharField(max_length=100, verbose_name='familyname')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
